#**Session 4 Python**

**By Eng| Ahmed Salim**

In [ ]:
x = 10
y = 10
x + y
x - y
x * y
x / y
x % y
x ** y
x // y

In [ ]:
x = 15
y = 3
x + y
x - y
x * y
x / y
x % y
x ** y
x // y

In [ ]:
x = 40
y = 5
x + y
x - y
x * y
x / y
x % y
x ** y
x // y

##**BuiltIn Function**

In [ ]:
print("s2")

s2

In [ ]:
x = 10
type(x)

int

In [ ]:
id(x)

11645640

In [ ]:
"".join(['a','h','m','e','d'])

'ahmed'

##**Pre Defined Function**

In [ ]:
# def function_name():
#   statements....
#   statements....
#   ........

# function_name()

# def function_name():
#   statements....
#   statements....
#   ........
#   return value1,value2,....

# function_name()
# v1,v2,.... = function_name()

# def function_name(params1,param2,....):
#   statements....
#   statements....
#   ........
#   return value1,value2,....

# function_name(arg1 , arg2 , ..... )
# v1,v2,... = function_name(arg1 , arg2 , ..... )
# v1_new,v2_new,... = function_name(arg1_new , arg2_new , ..... )

NO input and no return

In [ ]:
def say_hello():
  print("Hello,..")

In [ ]:
x = say_hello()

Hello,..

In [ ]:
x

input yes, no return

In [ ]:
def say_hello( name , age = 0 ):
  print("Hello,",name , "Your age is" , age)

In [ ]:
say_hello("s2")

Hello, s2 Your age is 0

In [ ]:
say_hello("Ahmed" , 30)

Hello, Ahmed Your age is 30

In [ ]:
say_hello(name="Ahmed" , age=30)

Hello, Ahmed Your age is 30

In [ ]:
say_hello(30 ,"Ahmed")

Hello, 30 Your age is Ahmed

In [ ]:
say_hello(age = 30 ,name =  "Ahmed")

Hello, Ahmed Your age is 30

input yes, return yes

In [ ]:
# add(5,1,2,3) # NameError: name 'add' is not defined

In [ ]:
# def add( num1:int  , num2:int ):
#   s = num1 + num2
#   return s

def add( num1   , num2 ):
  s = num1 + num2
  return s

In [ ]:
res = add(10,20)

In [ ]:
print(res)

30

In [ ]:
# lst = [2,3,4,3,4,5,6,7,8,8]
# return even [] , s_even "value"  , odd [] , s_odd "value"

In [ ]:
def even_odd_sum(lst):
  even = []
  odd = []
  s_even = 0
  s_odd = 0
  for i in lst:
    if i % 2 == 0:
      even.append(i)
      s_even += i
    else:
      odd.append(i)
      s_odd += i
  return even , s_even , odd , s_odd

In [ ]:
l = [1,2,3,2,3,4,3,4,5,6]
even , s_even , odd , s_odd = even_odd_sum(l)

In [ ]:
print("Even" , even , "Sum" , s_even)
print("Odd" , odd , "Sum" , s_odd)

Even [2, 2, 4, 4, 6] Sum 18
Odd [1, 3, 3, 3, 5] Sum 15

In [ ]:
def get_sum(seq):
  s = 0
  for i in seq:
    s += i
  return s

In [ ]:
def even_odd_sum(lst):
  even = []
  odd = []
  for i in lst:
    if i % 2 == 0 :
      even.append(i)
    else:
      odd.append(i)
  s_even = get_sum(even)
  s_odd = get_sum(odd)
  return even , s_even , odd , s_odd

In [ ]:
l = [1,2,3,2,3,4,3,4,5,6]
even , s_even , odd , s_odd = even_odd_sum(l)

In [ ]:
print("Even" , even , "Sum" , s_even)
print("Odd" , odd , "Sum" , s_odd)

Even [2, 2, 4, 4, 6] Sum 18
Odd [1, 3, 3, 3, 5] Sum 15

In [ ]:
def odd_even_lst(lst):
  even = []
  odd = []
  for i in lst:
    if i % 2 == 0 :
      even.append(i)
    else:
      odd.append(i)
  return even , odd

In [ ]:
def even_odd_sum(lst):
  even , odd = odd_even_lst(lst)
  s_even = get_sum(even)
  s_odd = get_sum(odd)
  return even , s_even , odd , s_odd

In [ ]:
even , s_even , odd , s_odd = even_odd_sum(l)

In [ ]:
print("Even" , even , "Sum" , s_even)
print("Odd" , odd , "Sum" , s_odd)

Even [2, 2, 4, 4, 6] Sum 18
Odd [1, 3, 3, 3, 5] Sum 15

In [ ]:
def add(num1 , num2):
  return num1 + num2
add(10,10)

20

In [ ]:
def add(num1 , num2 , num3):
  return num1 + num2 + num3
add(10,10 ,10)

30

In [ ]:
def add(num1 , num2 , num3 , num4):
  return num1 + num2 + num3 + num4
add(10,10 ,10 , 10)

40

In [ ]:
def add(*num):   # num  >>>  (val1 , val2, , , , ,)
  s = 0
  for i in num:
    s += i
  return s

In [ ]:
add()

0

In [ ]:
add(1)

1

In [ ]:
add(1,2)

3

In [ ]:
add(1,2,3)

6

In [ ]:
def obj(**b):
  k = b.keys()
  v = b.values()
  print(k)
  print(v)
  return b

In [ ]:
obj(name = "s2" , age = 30)

dict_keys(['name', 'age'])
dict_values(['s2', 30])

{'name': 's2', 'age': 30}

In [ ]:
import pandas as pd

In [ ]:
def dataframe(**params):
  df = pd.DataFrame(params)
  return df

In [ ]:
name = ['s1' , "s2" , "s3" ]
age = [ 20 ,  30 , 23]
dataframe(name = name , age = age).age

0    20
1    30
2    23
Name: age, dtype: int64

In [ ]:
dataframe(name = ["s2" , "s3"] , age = [30 , 23])

  name  age
0   s2   30
1   s3   23

In [ ]:
pd.DataFrame({'name': ['s2' , 's3'], 'age': [30 , 23]})

  name  age
0   s2   30
1   s3   23

In [ ]:
def check(num):
  if num % 2 == 0:
    return "Even"
  else:
    return "Odd"


lst = [1,2,3,4,3,4,5,4,5,6,5,6,7,8,9]

In [ ]:
for i in lst :
  print("the number",i ,"is", check(i))

the number 1 is Odd
the number 2 is Even
the number 3 is Odd
the number 4 is Even
the number 3 is Odd
the number 4 is Even
the number 5 is Odd
the number 4 is Even
the number 5 is Odd
the number 6 is Even
the number 5 is Odd
the number 6 is Even
the number 7 is Odd
the number 8 is Even
the number 9 is Odd

In [ ]:
[check(i) for i in lst ]

['Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd']

In [ ]:
# list(map(function , seq))
result = list(map(check , lst))

In [ ]:
result

['Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd',
 'Even',
 'Odd']

In [ ]:
res = map(check , lst)

In [ ]:
res

In [ ]:
print(list(res))

['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd']

In [ ]:
print(list(res))

[]

In [ ]:
def even_check(num):
  if num % 2 == 0:
    return num

In [ ]:
[ i for i in list(map(even_check , lst)) if i != None]

[2, 4, 4, 4, 6, 6, 8]

In [ ]:
def check_even(num):
  if num % 2 == 0:
    return True
  else:
    return False
list(filter(check_even , lst))

[2, 4, 4, 4, 6, 6, 8]

In [ ]:
list(filter( lambda num : num % 2 ==0 , lst))

[2, 4, 4, 4, 6, 6, 8]

In [ ]:
def check_odd(num):
  if num % 2 != 0:
    return True
list(filter(check_odd , lst))

[1, 3, 3, 5, 5, 5, 7, 9]

In [ ]:
list(filter( lambda num : num % 2 !=0 , lst))

[1, 3, 3, 5, 5, 5, 7, 9]

In [ ]:
x = lambda num : num % 2 ==0

In [ ]:
x(10)

True

In [ ]:
x(11)

False

In [ ]:
list(filter( lambda num : num % 2 ==0 , lst))

[2, 4, 4, 4, 6, 6, 8]