#**Session1 WebScraping s2**

**By Eng| Ahmed Salim**

##**Requests**

In [ ]:
# !pip install requests
import requests

In [ ]:
url = "https://books.toscrape.com/catalogue/page-1.html"

In [ ]:
response = requests.get(url)
response

In [ ]:
response.status_code

200

In [ ]:
print(response.text)

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:30" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="../static/oscar/favicon.ico" />






        <link rel="stylesheet" type="text/css" href="../static/oscar/css/styles.css" />

    <link rel="stylesheet" href="../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />
    <link rel="stylesheet" type="text/css" href="../static/oscar/css/datetimepicker.css" />












    </head>

    <body id="default" class="default">




    <header class="header container-fluid">
        <div class="page_inner">
            <div class="row">
                <div class="col-sm-8 h1"><a href="../index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>


            </div>
        </div>
    </header>



<div class="container-fluid page">
    <div class="page_inner">

    <ul class="breadcrumb">
        <li>
            <a href="../index.html">Home</a>
        </li>
        <li class="active">All products</li>
    </ul>

        <div class="row">

            <aside class="sidebar col-sm-4 col-md-3">

                <div id="promotions_left">

                </div>




        <div class="side_categories">
            <ul class="nav nav-list">

                    <li>
                        <a href="category/books_1/index.html">

                                Books

                        </a>

                        <ul>


                    <li>
                        <a href="category/books/travel_2/index.html">

                                Travel

                        </a>

                        </li>


                    <li>
                        <a href="category/books/mystery_3/index.html">

                                Mystery

                        </a>

                        </li>


                    <li>
                        <a href="category/books/historical-fiction_4/index.html">

                                Historical Fiction

                        </a>

                        </li>


                    <li>
                        <a href="category/books/sequential-art_5/index.html">

                                Sequential Art

                        </a>

                        </li>


                    <li>
                        <a href="category/books/classics_6/index.html">

                                Classics

                        </a>

                        </li>


                    <li>
                        <a href="category/books/philosophy_7/index.html">

                                Philosophy

                        </a>

                        </li>


                    <li>
                        <a href="category/books/romance_8/index.html">

                                Romance

                        </a>

                        </li>


                    <li>
                        <a href="category/books/womens-fiction_9/index.html">

                                Womens Fiction

                        </a>

                        </li>


                    <li>
                        <a href="category/books/fiction_10/index.html">

                                Fiction

                        </a>

                        </li>


                    <li>
                        <a href="category/books/childrens_11/index.html">

                                Childrens

                        </a>

                        </li>


                    <li>
                        <a href="category/books/religion_12/index.html">

                                Religion

                        </a>

                        </li>


                    <li>
                        <a href="category/books/nonfiction_13/index.html">

                                Nonfiction

                        </a>

                        </li>


                    <li>
                        <a href="category/books/music_14/index.html">

                                Music

                        </a>

                        </li>


                    <li>
                        <a href="category/books/default_15/index.html">

                                Default

                        </a>

                        </li>


                    <li>
                        <a href="category/books/science-fiction_16/index.html">

                                Science Fiction

                        </a>

                        </li>


                    <li>
                        <a href="category/books/sports-and-games_17/index.html">

                                Sports and Games

                        </a>

                        </li>


                    <li>
                        <a href="category/books/add-a-comment_18/index.html">

                                Add a comment

                        </a>

                        </li>


                    <li>
                        <a href="category/books/fantasy_19/index.html">

                                Fantasy

                        </a>

                        </li>


                    <li>
                        <a href="category/books/new-adult_20/index.html">

                                New Adult

                        </a>

                        </li>


                    <li>
                        <a href="category/books/young-adult_21/index.html">

                                Young Adult

                        </a>

                        </li>


                    <li>
                        <a href="category/books/science_22/index.html">

                                Science

                        </a>

                        </li>


                    <li>
                        <a href="category/books/poetry_23/index.html">

                                Poetry

                        </a>

                        </li>


                    <li>
                        <a href="category/books/paranormal_24/index.html">

                                Paranormal

                        </a>

                        </li>


                    <li>
                        <a href="category/books/art_25/index.html">

                                Art

                        </a>

                        </li>


                    <li>
                        <a href="category/books/psychology_26/index.html">

                                Psychology

                        </a>

                        </li>


                    <li>
                        <a href="category/books/autobiography_27/index.html">

                                Autobiography

                        </a>

                        </li>


                    <li>
                        <a href="category/books/parenting_28/index.html">

                                Parenting

                        </a>

                        </li>


                    <li>
                        <a href="category/books/adult-fiction_29/index.html">

                                Adult Fiction

                        </a>

                        </li>


                    <li>
                        <a href="category/books/humor_30/index.html">

                                Humor

                        </a>

                        </li>


                    <li>
                        <a href="category/books/horror_31/index.html">

                                Horror

                        </a>

                        </li>


                    <li>
                        <a href="category/books/history_32/index.html">

                                History

                        </a>

                        </li>


                    <li>
                        <a href="category/books/food-and-drink_33/index.html">

                                Food and Drink

                        </a>

                        </li>


                    <li>
                        <a href="category/books/christian-fiction_34/index.html">

                                Christian Fiction

                        </a>

                        </li>


                    <li>
                        <a href="category/books/business_35/index.html">

                                Business

                        </a>

                        </li>


                    <li>
                        <a href="category/books/biography_36/index.html">

                                Biography

                        </a>

                        </li>


                    <li>
                        <a href="category/books/thriller_37/index.html">

                                Thriller

                        </a>

                        </li>


                    <li>
                        <a href="category/books/contemporary_38/index.html">

                                Contemporary

                        </a>

                        </li>


                    <li>
                        <a href="category/books/spirituality_39/index.html">

                                Spirituality

                        </a>

                        </li>


                    <li>
                        <a href="category/books/academic_40/index.html">

                                Academic

                        </a>

                        </li>


                    <li>
                        <a href="category/books/self-help_41/index.html">

                                Self Help

                        </a>

                        </li>


                    <li>
                        <a href="category/books/historical_42/index.html">

                                Historical

                        </a>

                        </li>


                    <li>
                        <a href="category/books/christian_43/index.html">

                                Christian

                        </a>

                        </li>


                    <li>
                        <a href="category/books/suspense_44/index.html">

                                Suspense

                        </a>

                        </li>


                    <li>
                        <a href="category/books/short-stories_45/index.html">

                                Short Stories

                        </a>

                        </li>


                    <li>
                        <a href="category/books/novels_46/index.html">

                                Novels

                        </a>

                        </li>


                    <li>
                        <a href="category/books/health_47/index.html">

                                Health

                        </a>

                        </li>


                    <li>
                        <a href="category/books/politics_48/index.html">

                                Politics

                        </a>

                        </li>


                    <li>
                        <a href="category/books/cultural_49/index.html">

                                Cultural

                        </a>

                        </li>


                    <li>
                        <a href="category/books/erotica_50/index.html">

                                Erotica

                        </a>

                        </li>


                    <li>
                        <a href="category/books/crime_51/index.html">

                                Crime

                        </a>

                        </li>

                            </ul></li>


            </ul>
        </div>



            </aside>

            <div class="col-sm-8 col-md-9">

                <div class="page-header action">
                    <h1>All products</h1>
                </div>






<div id="messages">

</div>


                <div id="promotions">

                </div>


    <form method="get" class="form-horizontal">

        <div style="display:none">


        </div>




                    <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.




    </form>

        <section>
            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>

            <div>
                <ol class="row">

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="a-light-in-the-attic_1000/index.html"><img src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg" alt="A Light in the Attic" class="thumbnail"></a>


            </div>




                <p class="star-rating Three">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£51.77</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="tipping-the-velvet_999/index.html"><img src="../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg" alt="Tipping the Velvet" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>



            <div class="product_price">








        <p class="price_color">Â£53.74</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="soumission_998/index.html"><img src="../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg" alt="Soumission" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="soumission_998/index.html" title="Soumission">Soumission</a></h3>



            <div class="product_price">








        <p class="price_color">Â£50.10</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="sharp-objects_997/index.html"><img src="../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg" alt="Sharp Objects" class="thumbnail"></a>


            </div>




                <p class="star-rating Four">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>



            <div class="product_price">








        <p class="price_color">Â£47.82</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="sapiens-a-brief-history-of-humankind_996/index.html"><img src="../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg" alt="Sapiens: A Brief History of Humankind" class="thumbnail"></a>


            </div>




                <p class="star-rating Five">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>




            <h3><a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>



            <div class="product_price">








        <p class="price_color">Â£54.23</p>


<p class="instock availability">
    <i class="icon-ok"></i>

        In stock

</p>










    <form>
        <button type="submit" class="btn btn-primary btn-block" data-loading-text="Adding...">Add to basket</button>
    </form>



            </div>

    </article>

</li>

                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">






    <article class="product_pod">

            <div class="image_container">


                    <a href="the-requiem-red_995/index.html"><img src="../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg" alt="The Requiem Red" class="thumbnail"></a>


            </div>




                <p class="star-rating One">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                </p>





##**Beautiful Soup**

In [ ]:
# !pip install beautifulsoup4

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(response.text, 'html.parser')

In [ ]:
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:30" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="../static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="../index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="../index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             Â£33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">
             The Coming Woman: A ...

In [ ]:
print(soup.title.get_text())

    All products | Books to Scrape - Sandbox

In [ ]:
print(soup.title.get_text(strip=True))

All products | Books to Scrape - Sandbox

In [ ]:
# soup.title.get_text().strip().split()

In [ ]:
soup.header

<header class="header container-fluid">
<div class="page_inner">
<div class="row">
<div class="col-sm-8 h1"><a href="../index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>
</div>
</div>
</header>

In [ ]:
print(soup.find('div').prettify())

<div class="page_inner">
 <div class="row">
  <div class="col-sm-8 h1">
   <a href="../index.html">
    Books to Scrape
   </a>
   <small>
    We love being scraped!
   </small>
  </div>
 </div>
</div>

In [ ]:
soup.find('div').get_text(strip=True)

'Books to ScrapeWe love being scraped!'

In [ ]:
soup.find_all('div')

[<div class="page_inner">
 <div class="row">
 <div class="col-sm-8 h1"><a href="../index.html">Books to Scrape</a><small> We love being scraped!</small>
 </div>
 </div>
 </div>,
 <div class="row">
 <div class="col-sm-8 h1"><a href="../index.html">Books to Scrape</a><small> We love being scraped!</small>
 </div>
 </div>,
 <div class="col-sm-8 h1"><a href="../index.html">Books to Scrape</a><small> We love being scraped!</small>
 </div>,
 <div class="container-fluid page">
 <div class="page_inner">
 <ul class="breadcrumb">
 <li>
 <a href="../index.html">Home</a>
 </li>
 <li class="active">All products</li>
 </ul>
 <div class="row">
 <aside class="sidebar col-sm-4 col-md-3">
 <div id="promotions_left">
 </div>
 <div class="side_categories">
 <ul class="nav nav-list">
 <li>
 <a href="category/books_1/index.html">

                                 Books

                         </a>
 <ul>
 <li>
 <a href="category/books/travel_2/index.html">

                                 Travel

                         </a>
 </li>
 <li>
 <a href="category/books/mystery_3/index.html">

                                 Mystery

                         </a>
 </li>
 <li>
 <a href="category/books/historical-fiction_4/index.html">

                                 Historical Fiction

                         </a>
 </li>
 <li>
 <a href="category/books/sequential-art_5/index.html">

                                 Sequential Art

                         </a>
 </li>
 <li>
 <a href="category/books/classics_6/index.html">

                                 Classics

                         </a>
 </li>
 <li>
 <a href="category/books/philosophy_7/index.html">

                                 Philosophy

                         </a>
 </li>
 <li>
 <a href="category/books/romance_8/index.html">

                                 Romance

                         </a>
 </li>
 <li>
 <a href="category/books/womens-fiction_9/index.html">

                                 Womens Fiction

                         </a>
 </li>
 <li>
 <a href="category/books/fiction_10/index.html">

                                 Fiction

                         </a>
 </li>
 <li>
 <a href="category/books/childrens_11/index.html">

                                 Childrens

                         </a>
 </li>
 <li>
 <a href="category/books/religion_12/index.html">

                                 Religion

                         </a>
 </li>
 <li>
 <a href="category/books/nonfiction_13/index.html">

                                 Nonfiction

                         </a>
 </li>
 <li>
 <a href="category/books/music_14/index.html">

                                 Music

                         </a>
 </li>
 <li>
 <a href="category/books/default_15/index.html">

                                 Default

                         </a>
 </li>
 <li>
 <a href="category/books/science-fiction_16/index.html">

                                 Science Fiction

                         </a>
 </li>
 <li>
 <a href="category/books/sports-and-games_17/index.html">

                                 Sports and Games

                         </a>
 </li>
 <li>
 <a href="category/books/add-a-comment_18/index.html">

                                 Add a comment

                         </a>
 </li>
 <li>
 <a href="category/books/fantasy_19/index.html">

                                 Fantasy

                         </a>
 </li>
 <li>
 <a href="category/books/new-adult_20/index.html">

                                 New Adult

                         </a>
 </li>
 <li>
 <a href="category/books/young-adult_21/index.html">

                                 Young Adult

                         </a>
 </li>
 <li>
 <a href="category/books/science_22/index.html">

                                 Science

                         </a>
 </li>
 <li>
 <a href="category/books/poetry_23/index.html">

                                 Poetry

                         </a>
 </li>
 <li>
 <a href="category/books/paranormal_24/index.html">

                                 Paranormal

                         </a>
 </li>
 <li>
 <a href="category/books/art_25/index.html">

                                 Art

                         </a>
 </li>
 <li>
 <a href="category/books/psychology_26/index.html">

                                 Psychology

                         </a>
 </li>
 <li>
 <a href="category/books/autobiography_27/index.html">

                                 Autobiography

                         </a>
 </li>
 <li>
 <a href="category/books/parenting_28/index.html">

                                 Parenting

                         </a>
 </li>
 <li>
 <a href="category/books/adult-fiction_29/index.html">

                                 Adult Fiction

                         </a>
 </li>
 <li>
 <a href="category/books/humor_30/index.html">

                                 Humor

                         </a>
 </li>
 <li>
 <a href="category/books/horror_31/index.html">

                                 Horror

                         </a>
 </li>
 <li>
 <a href="category/books/history_32/index.html">

                                 History

                         </a>
 </li>
 <li>
 <a href="category/books/food-and-drink_33/index.html">

                                 Food and Drink

                         </a>
 </li>
 <li>
 <a href="category/books/christian-fiction_34/index.html">

                                 Christian Fiction

                         </a>
 </li>
 <li>
 <a href="category/books/business_35/index.html">

                                 Business

                         </a>
 </li>
 <li>
 <a href="category/books/biography_36/index.html">

                                 Biography

                         </a>
 </li>
 <li>
 <a href="category/books/thriller_37/index.html">

                                 Thriller

                         </a>
 </li>
 <li>
 <a href="category/books/contemporary_38/index.html">

                                 Contemporary

                         </a>
 </li>
 <li>
 <a href="category/books/spirituality_39/index.html">

                                 Spirituality

                         </a>
 </li>
 <li>
 <a href="category/books/academic_40/index.html">

                                 Academic

                         </a>
 </li>
 <li>
 <a href="category/books/self-help_41/index.html">

                                 Self Help

                         </a>
 </li>
 <li>
 <a href="category/books/historical_42/index.html">

                                 Historical

                         </a>
 </li>
 <li>
 <a href="category/books/christian_43/index.html">

                                 Christian

                         </a>
 </li>
 <li>
 <a href="category/books/suspense_44/index.html">

                                 Suspense

                         </a>
 </li>
 <li>
 <a href="category/books/short-stories_45/index.html">

                                 Short Stories

                         </a>
 </li>
 <li>
 <a href="category/books/novels_46/index.html">

                                 Novels

                         </a>
 </li>
 <li>
 <a href="category/books/health_47/index.html">

                                 Health

                         </a>
 </li>
 <li>
 <a href="category/books/politics_48/index.html">

                                 Politics

                         </a>
 </li>
 <li>
 <a href="category/books/cultural_49/index.html">

                                 Cultural

                         </a>
 </li>
 <li>
 <a href="category/books/erotica_50/index.html">

                                 Erotica

                         </a>
 </li>
 <li>
 <a href="category/books/crime_51/index.html">

                                 Crime

                         </a>
 </li>
 </ul></li>
 </ul>
 </div>
 </aside>
 <div class="col-sm-8 col-md-9">
 <div class="page-header action">
 <h1>All products</h1>
 </div>
 <div id="messages">
 </div>
 <div id="promotions">
 </div>
 <form class="form-horizontal" method="get">
 <div style="display:none">
 </div>
 <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.




     </form>
 <section>
 <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>
 <div>
 <ol class="row">
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="../media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="../media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="../media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="../media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.23</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="../media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.65</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="../media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.34</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="../media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.93</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="../media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.60</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="../media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.15</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="../media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£13.99</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="../media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
 <div class="product_price">
 <p class="price_color">Â£20.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>
 </li>
 <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
 <div class="image_container">
 <a href="set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="../media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
 </div>
 <p class="star-rating Five">

In [ ]:
side_categories = soup.find('div' , class_='side_categories').find_all('a')

In [ ]:
print(soup.find('div' , class_='side_categories').find_all('a')[0])

<a href="category/books_1/index.html">

                                Books

                        </a>

In [ ]:
print(soup.find('div' , class_='side_categories').find_all('a')[0].get_text(strip=True))

Books

In [ ]:
res = [ i.get_text() for i in side_categories]
res

['\n                            \n                                Books\n                            \n                        ',
 '\n                            \n                                Travel\n                            \n                        ',
 '\n                            \n                                Mystery\n                            \n                        ',
 '\n                            \n                                Historical Fiction\n                            \n                        ',
 '\n                            \n                                Sequential Art\n                            \n                        ',
 '\n                            \n                                Classics\n                            \n                        ',
 '\n                            \n                                Philosophy\n                            \n                        ',
 '\n                            \n                                Romance\n                            \n                        ',
 '\n                            \n                                Womens Fiction\n                            \n                        ',
 '\n                            \n                                Fiction\n                            \n                        ',
 '\n                            \n                                Childrens\n                            \n                        ',
 '\n                            \n                                Religion\n                            \n                        ',
 '\n                            \n                                Nonfiction\n                            \n                        ',
 '\n                            \n                                Music\n                            \n                        ',
 '\n                            \n                                Default\n                            \n                        ',
 '\n                            \n                                Science Fiction\n                            \n                        ',
 '\n                            \n                                Sports and Games\n                            \n                        ',
 '\n                            \n                                Add a comment\n                            \n                        ',
 '\n                            \n                                Fantasy\n                            \n                        ',
 '\n                            \n                                New Adult\n                            \n                        ',
 '\n                            \n                                Young Adult\n                            \n                        ',
 '\n                            \n                                Science\n                            \n                        ',
 '\n                            \n                                Poetry\n                            \n                        ',
 '\n                            \n                                Paranormal\n                            \n                        ',
 '\n                            \n                                Art\n                            \n                        ',
 '\n                            \n                                Psychology\n                            \n                        ',
 '\n                            \n                                Autobiography\n                            \n                        ',
 '\n                            \n                                Parenting\n                            \n                        ',
 '\n                            \n                                Adult Fiction\n                            \n                        ',
 '\n                            \n                                Humor\n                            \n                        ',
 '\n                            \n                                Horror\n                            \n                        ',
 '\n                            \n                                History\n                            \n                        ',
 '\n                            \n                                Food and Drink\n                            \n                        ',
 '\n                            \n                                Christian Fiction\n                            \n                        ',
 '\n                            \n                                Business\n                            \n                        ',
 '\n                            \n                                Biography\n                            \n                        ',
 '\n                            \n                                Thriller\n                            \n                        ',
 '\n                            \n                                Contemporary\n                            \n                        ',
 '\n                            \n                                Spirituality\n                            \n                        ',
 '\n                            \n                                Academic\n                            \n                        ',
 '\n                            \n                                Self Help\n                            \n                        ',
 '\n                            \n                                Historical\n                            \n                        ',
 '\n                            \n                                Christian\n                            \n                        ',
 '\n                            \n                                Suspense\n                            \n                        ',
 '\n                            \n                                Short Stories\n                            \n                        ',
 '\n                            \n                                Novels\n                            \n                        ',
 '\n                            \n                                Health\n                            \n                        ',
 '\n                            \n                                Politics\n                            \n                        ',
 '\n                            \n                                Cultural\n                            \n                        ',
 '\n                            \n                                Erotica\n                            \n                        ',
 '\n                            \n                                Crime\n                            \n                        ']

In [ ]:
list(map( lambda i : i.strip() , res))

['Books',
 'Travel',
 'Mystery',
 'Historical Fiction',
 'Sequential Art',
 'Classics',
 'Philosophy',
 'Romance',
 'Womens Fiction',
 'Fiction',
 'Childrens',
 'Religion',
 'Nonfiction',
 'Music',
 'Default',
 'Science Fiction',
 'Sports and Games',
 'Add a comment',
 'Fantasy',
 'New Adult',
 'Young Adult',
 'Science',
 'Poetry',
 'Paranormal',
 'Art',
 'Psychology',
 'Autobiography',
 'Parenting',
 'Adult Fiction',
 'Humor',
 'Horror',
 'History',
 'Food and Drink',
 'Christian Fiction',
 'Business',
 'Biography',
 'Thriller',
 'Contemporary',
 'Spirituality',
 'Academic',
 'Self Help',
 'Historical',
 'Christian',
 'Suspense',
 'Short Stories',
 'Novels',
 'Health',
 'Politics',
 'Cultural',
 'Erotica',
 'Crime']

In [ ]:
import pandas as pd
df = pd.DataFrame(res)

In [ ]:
df[0][0]

'\n                            \n                                Books\n                            \n                        '

In [ ]:
df["side_categories"] = df[0].map(lambda i : i.strip())

In [ ]:
df.drop(columns=[0], inplace=True)

In [ ]:
df

       side_categories
0                Books
1               Travel
2              Mystery
3   Historical Fiction
4       Sequential Art
5             Classics
6           Philosophy
7              Romance
8       Womens Fiction
9              Fiction
10           Childrens
11            Religion
12          Nonfiction
13               Music
14             Default
15     Science Fiction
16    Sports and Games
17       Add a comment
18             Fantasy
19           New Adult
20         Young Adult
21             Science
22              Poetry
23          Paranormal
24                 Art
25          Psychology
26       Autobiography
27           Parenting
28       Adult Fiction
29               Humor
30              Horror
31             History
32      Food and Drink
33   Christian Fiction
34            Business
35           Biography
36            Thriller
37        Contemporary
38        Spirituality
39            Academic
40           Self Help
41          Historical
42           Christian
43            Suspense
44       Short Stories
45              Novels
46              Health
47            Politics
48            Cultural
49             Erotica
50               Crime

In [ ]:
books = soup.find_all('article' , class_='product_pod')

In [ ]:
soup.find_all('article' , class_='product_pod')[0]

<article class="product_pod">
<div class="image_container">
<a href="a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [ ]:
soup.find_all('article' , class_='product_pod')[0].find('h3').get_text()

'A Light in the ...'

In [ ]:
soup.find_all('article' , class_='product_pod')[0].find('p' , class_='price_color').get_text()

'Â£51.77'

In [ ]:
soup.find_all('article' , class_='product_pod')[0].find('p' , class_='instock availability').get_text(strip=True)

'In stock'

In [ ]:
def extract_book_info(listofbooks):
    book_name = []
    price = []
    availability = []
    for book in listofbooks:
        book_name.append(book.find('h3').get_text())
        price.append(book.find('p' , class_='price_color').get_text())
        availability.append(book.find('p' , class_='instock availability').get_text(strip=True))
    return book_name , price , availability

In [ ]:
book_name , price , availability = extract_book_info(books)

In [ ]:
pd.DataFrame({'book_name':book_name , 'price':price , 'availability':availability})

                                book_name    price availability
0                      A Light in the ...  Â£51.77     In stock
1                      Tipping the Velvet  Â£53.74     In stock
2                              Soumission  Â£50.10     In stock
3                           Sharp Objects  Â£47.82     In stock
4            Sapiens: A Brief History ...  Â£54.23     In stock
5                         The Requiem Red  Â£22.65     In stock
6            The Dirty Little Secrets ...  Â£33.34     In stock
7                 The Coming Woman: A ...  Â£17.93     In stock
8                     The Boys in the ...  Â£22.60     In stock
9                         The Black Maria  Â£52.15     In stock
10  Starving Hearts (Triangular Trade ...  Â£13.99     In stock
11                  Shakespeare's Sonnets  Â£20.66     In stock
12                            Set Me Free  Â£17.46     In stock
13    Scott Pilgrim's Precious Little ...  Â£52.29     In stock
14                      Rip it Up and ...  Â£35.02     In stock
15                  Our Band Could Be ...  Â£57.25     In stock
16                                   Olio  Â£23.88     In stock
17        Mesaerion: The Best Science ...  Â£37.59     In stock
18           Libertarianism for Beginners  Â£51.33     In stock
19                It's Only the Himalayas  Â£45.17     In stock